import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { useEffect, useState } from "react";
import axios from "axios";
import Link from "next/link";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

interface pokemonProps {
  id: string;
  url: string;
  name: string;
  imageUrl:string;

}

export default function Home() {

  const [pokemons, setPokemons] = useState<pokemonProps[]>([]);
  const router = useRouter()

  useEffect(() => {
    const fetchData = async () => {
        try {
            const response = await axios.get(`https://pokeapi.co/api/v2/type`);
            setPokemons(response?.data?.results);
        } catch (error) {
            console.error('Error fetching data:', error);
        }
    };

    fetchData();
}, []);


const handleSelect = (url: string) => {
  const number = url.split('/').slice(-2, -1)[0]; 
  router.push(`/pokemon/${number}`); 
};


 

  return (
    <>
      <Head>
        <title>Pokemon Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
       <Navbar/>
       <div >
        <div className={styles.pokemontext}>POKEMON CATEGORIES/TYPE</div>
       <div className={styles.pokemongrid}>
        {pokemons &&
            pokemons.map((pokemon, index) => (
                <div className={styles.eachpokemon} key={index}>
                    <ul>
                      <Link className={styles.category} href={`/pokemon/${pokemon.url.split('/').slice(-2, -1)[0]}`}>
                        <li onClick={() => handleSelect(pokemon.url)}>{pokemon.name}</li>
                    </Link>
                        
                    </ul>
                </div>
            ))}
    </div>
       </div>
       <Footer/>
      </main>
    </>
  );
}
