import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { useEffect, useState } from "react";
import axios from "axios";
import Link from "next/link";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

interface pokemonProps {
  id: string;
  url: string;
  name: string;
  imageUrl:string;

}

export default function Pokemon() {

  const [selectedPokemon, setSelectedPokemon] = useState<string | null>(null);
  const router = useRouter();
  const { url } = router.query;

  console.log('name', url)




useEffect(() => {
    const handleSelect = async (url: string) => {
        try {
            const response = await axios.get(url);
            setSelectedPokemon(response.data);
            console.log('Selected Pokemon:', response.data);
        } catch (error) {
            console.error('Error fetching data:', error);
        }
      };

    
}, []);

 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
       <Navbar/>
       <div className="my-5">
       <div className={styles.pokemongrid}>

        HERE ARE THE POKEMONS
        {/* {pokemons &&
            pokemons.map((pokemon, index) => (
                <div className={styles.eachpokemon} key={index}>
                    <ul>
                      <Link href={`/pokemon/${pokemon.url}`}>
                      </Link>
                        <li onClick={() => handleSelect(pokemon.url)}>{pokemon.name}</li>
                    </ul>
                </div>
            ))} */}
    </div>
       </div>
       <Footer/>
      </main>
    </>
  );
}
